traefik:
  image: traefik
  restart: always
  command: --api --docker
  ports:
    - 80:80
    - 443:443
    - 8080:8080
  networks:
    - web
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/traefik/traefik.toml:/traefik.toml
    - /opt/traefik/acme.json:/acme.json
  container_name: traefik
